# Generated by Django 4.2.2 on 2024-02-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_remove_leave_is_approved_remove_leave_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='leavesapplied',
            field=models.IntegerField(default=0),
        ),
    ]
